## Pandas

In [1]:
import pandas as pd

In [2]:
A = pd.Series([2,3,4,5], index = ['a', 'b', 'c', 'd'])

In [3]:
A.values

array([2, 3, 4, 5])

In [4]:
type(A.values)

numpy.ndarray

In [5]:
type(A)

pandas.Series

In [6]:
A.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [7]:
A['a']

np.int64(2)

In [8]:
A['a':'c']

a    2
b    3
c    4
dtype: int64

In [9]:
grades_dict = {'A':4,'B':3.5,'C':3,'D':2.5}
grades = pd.Series(grades_dict)

In [10]:
grades.values

array([4. , 3.5, 3. , 2.5])

In [11]:
grades.index

Index(['A', 'B', 'C', 'D'], dtype='str')

In [12]:
marks_dict = {'A':85,'B':75,'C':65,'D':55}
marks = pd.Series(marks_dict)

In [13]:
marks

A    85
B    75
C    65
D    55
dtype: int64

In [14]:
marks['A']

np.int64(85)

In [15]:
marks[0:2]

A    85
B    75
dtype: int64

In [16]:
D = pd.DataFrame({'marks':marks,'grades':grades})

In [17]:
D

,marks,grades
A,85,4.0
B,75,3.5
C,65,3.0
D,55,2.5


In [18]:
D.T

,A,B,C,D
marks,85.0,75.0,65.0,55.0
grades,4.0,3.5,3.0,2.5


In [19]:
D.values

array([[85. ,  4. ],
       [75. ,  3.5],
       [65. ,  3. ],
       [55. ,  2.5]])

In [20]:
D.values[2,0]

np.float64(65.0)

In [21]:
D.columns

Index(['marks', 'grades'], dtype='str')

In [22]:
D['ScaledMarks'] = 100*(D['marks']/90)

In [23]:
D

,marks,grades,ScaledMarks
A,85,4.0,94.444444
B,75,3.5,83.333333
C,65,3.0,72.222222
D,55,2.5,61.111111


In [24]:
del D['ScaledMarks']

In [25]:
D

,marks,grades
A,85,4.0
B,75,3.5
C,65,3.0
D,55,2.5


In [26]:
G = D[D['marks'] >70]

In [27]:
G

,marks,grades
A,85,4.0
B,75,3.5


# Pandas NaN

In [28]:
A = pd.DataFrame([{'a':1,'b':4},{'b':-3,'c':9}])

In [29]:
A

,a,b,c
0,1.0,4,NaN
1,NaN,-3,9.0


In [30]:
A.fillna(0)

,a,b,c
0,1.0,4,0.0
1,0.0,-3,9.0


# implicit and explicit index

In [31]:
A1 = pd.Series(['a','b','c'], index = [1,3,5])

In [32]:
A1[1]

'a'

In [33]:
A1[1:3]

3    b
5    c
dtype: str

In [34]:
A1.loc[1:3]

1    a
3    b
dtype: str

In [35]:
A1.iloc[1:3]

3    b
5    c
dtype: str

In [36]:
D.iloc[2,:]

marks     65.0
grades     3.0
Name: C, dtype: float64

In [37]:
D.iloc[::-1,:]

,marks,grades
D,55,2.5
C,65,3.0
B,75,3.5
A,85,4.0


In [38]:
from sklearn.impute import SimpleImputer

In [39]:
df = pd.read_csv('C:/Users/Keenan/Documents/git repos/Python-practice/Pandas/data/covid_19_data.csv')

In [40]:
df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0


In [41]:
df.head(10)

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
5,6,01/22/2020,Guangdong,Mainland China,1/22/2020 17:00,26.0,0.0,0.0
6,7,01/22/2020,Guangxi,Mainland China,1/22/2020 17:00,2.0,0.0,0.0
7,8,01/22/2020,Guizhou,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
8,9,01/22/2020,Hainan,Mainland China,1/22/2020 17:00,4.0,0.0,0.0
9,10,01/22/2020,Hebei,Mainland China,1/22/2020 17:00,1.0,0.0,0.0


In [42]:
df.drop(['SNo','Last Update'], axis = 1, inplace = True)

In [43]:
df.head()

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered
0,01/22/2020,Anhui,Mainland China,1.0,0.0,0.0
1,01/22/2020,Beijing,Mainland China,14.0,0.0,0.0
2,01/22/2020,Chongqing,Mainland China,6.0,0.0,0.0
3,01/22/2020,Fujian,Mainland China,1.0,0.0,0.0
4,01/22/2020,Gansu,Mainland China,0.0,0.0,0.0


In [44]:
df.rename(columns={'ObservationDate':'Date','Province/State':'Province','Country/Region':'Country'},inplace=True)

In [45]:
df.head()

,Date,Province,Country,Confirmed,Deaths,Recovered
0,01/22/2020,Anhui,Mainland China,1.0,0.0,0.0
1,01/22/2020,Beijing,Mainland China,14.0,0.0,0.0
2,01/22/2020,Chongqing,Mainland China,6.0,0.0,0.0
3,01/22/2020,Fujian,Mainland China,1.0,0.0,0.0
4,01/22/2020,Gansu,Mainland China,0.0,0.0,0.0


In [46]:
df['Date'] = pd.to_datetime(df['Date'])

In [47]:
df.head()

,Date,Province,Country,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1.0,0.0,0.0
1,2020-01-22,Beijing,Mainland China,14.0,0.0,0.0
2,2020-01-22,Chongqing,Mainland China,6.0,0.0,0.0
3,2020-01-22,Fujian,Mainland China,1.0,0.0,0.0
4,2020-01-22,Gansu,Mainland China,0.0,0.0,0.0


In [48]:
df.describe()

,Date,Confirmed,Deaths,Recovered
count,306429,3.064290e+05,306429.000000,3.064290e+05
mean,2020-11-06 01:54:54.146442,8.567091e+04,2036.403268,5.042029e+04
min,2020-01-22 00:00:00,-3.028440e+05,-178.000000,-8.544050e+05
25%,2020-07-30 00:00:00,1.042000e+03,13.000000,1.100000e+01
50%,2020-11-10 00:00:00,1.037500e+04,192.000000,1.751000e+03
75%,2021-02-18 00:00:00,5.075200e+04,1322.000000,2.027000e+04
max,2021-05-29 00:00:00,5.863138e+06,112385.000000,6.399531e+06
std,NaN,2.775516e+05,6410.938048,2.015124e+05


In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype         
---  ------     --------------   -----         
 0   Date       306429 non-null  datetime64[us]
 1   Province   228326 non-null  str           
 2   Country    306429 non-null  str           
 3   Confirmed  306429 non-null  float64       
 4   Deaths     306429 non-null  float64       
 5   Recovered  306429 non-null  float64       
dtypes: datetime64[us](1), float64(3), str(2)
memory usage: 14.0 MB


In [50]:
df.fillna('NA')

,Date,Province,Country,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1.0,0.0,0.0
1,2020-01-22,Beijing,Mainland China,14.0,0.0,0.0
2,2020-01-22,Chongqing,Mainland China,6.0,0.0,0.0
3,2020-01-22,Fujian,Mainland China,1.0,0.0,0.0
4,2020-01-22,Gansu,Mainland China,0.0,0.0,0.0
...,...,...,...,...,...,...
306424,2021-05-29,Zaporizhia Oblast,Ukraine,102641.0,2335.0,95289.0
306425,2021-05-29,Zeeland,Netherlands,29147.0,245.0,0.0
306426,2021-05-29,Zhejiang,Mainland China,1364.0,1.0,1324.0
306427,2021-05-29,Zhytomyr Oblast,Ukraine,87550.0,1738.0,83790.0


In [51]:
df.head(20)

,Date,Province,Country,Confirmed,Deaths,Recovered
0,2020-01-22,Anhui,Mainland China,1.0,0.0,0.0
1,2020-01-22,Beijing,Mainland China,14.0,0.0,0.0
2,2020-01-22,Chongqing,Mainland China,6.0,0.0,0.0
3,2020-01-22,Fujian,Mainland China,1.0,0.0,0.0
4,2020-01-22,Gansu,Mainland China,0.0,0.0,0.0
5,2020-01-22,Guangdong,Mainland China,26.0,0.0,0.0
6,2020-01-22,Guangxi,Mainland China,2.0,0.0,0.0
7,2020-01-22,Guizhou,Mainland China,1.0,0.0,0.0
8,2020-01-22,Hainan,Mainland China,4.0,0.0,0.0
9,2020-01-22,Hebei,Mainland China,1.0,0.0,0.0


In [52]:
imputer = SimpleImputer(strategy = 'contant')

In [53]:
imputer

,"missing_values missing_values: int, float, str, np.nan, None or pandas.NA, default=np.nanThe placeholder for the missing values. All occurrences of`missing_values` will be imputed. For pandas' dataframes withnullable integer dtypes with missing values, `missing_values`can be set to either `np.nan` or `pd.NA`.",nan
,"strategy strategy: str or Callable, default='mean'The imputation strategy.- If ""mean"", then replace missing values using the mean along each column. Can only be used with numeric data.- If ""median"", then replace missing values using the median along each column. Can only be used with numeric data.- If ""most_frequent"", then replace missing using the most frequent value along each column. Can be used with strings or numeric data. If there is more than one such value, only the smallest is returned.- If ""constant"", then replace missing values with fill_value. Can be used with strings or numeric data.- If an instance of Callable, then replace missing values using the scalar statistic returned by running the callable over a dense 1d array containing non-missing values of each column... versionadded:: 0.20 strategy=""constant"" for fixed value imputation... versionadded:: 1.5 strategy=callable for custom value imputation.",'contant'
,"fill_value fill_value: str or numerical value, default=NoneWhen strategy == ""constant"", `fill_value` is used to replace alloccurrences of missing_values. For string or object data types,`fill_value` must be a string.If `None`, `fill_value` will be 0 when imputing numericaldata and ""missing_value"" for strings or object data types.",None
,"copy copy: bool, default=TrueIf True, a copy of X will be created. If False, imputation willbe done in-place whenever possible. Note that, in the following cases,a new copy will always be made, even if `copy=False`:- If `X` is not an array of floating values;- If `X` is encoded as a CSR matrix;- If `add_indicator=True`.",True
,"add_indicator add_indicator: bool, default=FalseIf True, a :class:`MissingIndicator` transform will stack onto outputof the imputer's transform. This allows a predictive estimatorto account for missingness despite imputation. If a feature has nomissing values at fit/train time, the feature won't appear onthe missing indicator even if there are missing values attransform/test time.",False
,"keep_empty_features keep_empty_features: bool, default=FalseIf True, features that consist exclusively of missing values when`fit` is called are returned in results when `transform` is called.The imputed value is always `0` except when `strategy=""constant""`in which case `fill_value` will be used instead... versionadded:: 1.2",False
